[package]
name = "dhcpq"
version = "0.1.0"
authors = [
  "Thomas Wickham  <mackwic@gmail.com>",
  "Johann Aurieres <thejohkill@hotmail.fr>"
]

[dependencies]
mio = "0.5"
nom = "1.2"
quick-error = "1.1"

